from pathlib import Path
from .config import PROBLEMS_DIR_NAME, WORKSPACE_DIR_NAME, DATA_DIR_NAME, PROGRESS_FILENAME, NOTES_DIR_NAME

ROOT = Path(__file__).resolve().parent.parent
PROBLEMS_DIR = ROOT / PROBLEMS_DIR_NAME
WORKSPACE = ROOT / WORKSPACE_DIR_NAME
DATA = ROOT / DATA_DIR_NAME
PROGRESS_FILE = DATA / PROGRESS_FILENAME
SUBMISSIONS_FILE = DATA / "submissions.json"
NOTES_DIR = ROOT / NOTES_DIR_NAME
